export const API_ENDPOINTS = {
  chat: "/v1/chat",
  chatStream: "/v1/chat/stream",
  agents: "/v1/agents",
  agentDetail: (agentId: string) => `/v1/agents/${agentId}`,
  agentChat: (agentId: string) => `/v1/agents/${agentId}/chat`,
  agentChatStream: (agentId: string) => `/v1/agents/${agentId}/chat/stream`,
  conversations: "/v1/conversations",
  conversationDetail: (conversationId: string) => `/v1/conversations/${conversationId}`,
  agentRuns: "/v1/agent/runs",
  agentRunDetail: (runId: string) => `/v1/agent/runs/${runId}`,
  files: "/v1/files",
  fileUpload: "/v1/files/upload",
  fileDetail: (fileId: string) => `/v1/files/${fileId}`,
  fileDownload: (fileId: string) => `/v1/files/${fileId}/download`,
} as const;
