export const API_ENDPOINTS = {
  chat: "/v1/chat",
  chatStream: "/v1/chat/stream",
  chatResume: "/v1/chat/resume",
  chatResumeStream: "/v1/chat/resume/stream",
  agents: "/v1/agents",
  agentDetail: (agentId: string) => `/v1/agents/${agentId}`,
  agentChat: (agentId: string) => `/v1/agents/${agentId}/chat`,
  agentChatStream: (agentId: string) => `/v1/agents/${agentId}/chat/stream`,
  conversations: "/v1/conversations",
  conversationDetail: (conversationId: string) => `/v1/conversations/${conversationId}`,
  agentStatus: "/v1/agent/status",
  agentResume: "/v1/agent/resume",
  agentInterrupt: "/v1/agent/interrupt",
  agentCancel: "/v1/agent/cancel",
  agentRuns: "/v1/agent/runs",
  agentRunDetail: (runId: string) => `/v1/agent/runs/${runId}`,
  files: "/v1/files",
  fileUpload: "/v1/files/upload",
  fileDetail: (fileId: string) => `/v1/files/${fileId}`,
  fileDownload: (fileId: string) => `/v1/files/${fileId}/download`,
} as const;
